### ISSUE TITLE
Error: reason is not defined

### ISSUE THREAD

**Issue by bharveyfuture** [willheslam/unistyle-loader#1]
In the event that an exception is thrown, you get the error `reason is not defined` when the code drops into the catch statement.

`reason` is only defined within the try statement which causes this error.

However, as the loader is designed to be part of a chain of loaders, should try catch be used?

**Comment by willheslam** [comment]
Nice catch! (excuse the pun)
In this case the try/catch is necessary to catch any exceptions thrown by: this.exec(source)
(say, invalid js)

Normally it would be fine to let the exception bubble up, but because unistyle is an async API, the loader has to be too - (this is what calling this.async() turns on), which disables the usual exception bubbling mechanism. You have to explicitly call 'callback' with the first argument as the error instead.

This is fixed in 1.0.5 - please update when you can. :) Thanks!
